image: viaduck/ci

stages:
    - build         # contains build and test and deploy

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    ICU_BUILD_VERSION: "61.1"
    PREBUILTS_REPO: "https://$GIT_USER:$GIT_PASSWORD@gl.viaduck.org/viaduck/icu-prebuilts.git"
    ANDROID_PLATFORM: "android-26"
    ANDROID_NDK: "/android/ndk"
    
build:linux-x86_64:
    script:
        - mkdir build-linux-x86_64
        - cd build-linux-x86_64
        - cmake ../ -DBUILD_ICU=ON
        - make
        - ../scripts/commit_result.sh x86_64-linux icu_host
    stage: build
    only:
        - master

build:windows-x86_64:
    image: viaduck/ci:mingw
    script:
        - mkdir build-windows-x86_64
        - cd build-windows-x86_64
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=x86_64-w64-mingw32 -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DCMAKE_TOOLCHAIN_FILE=../cmake-modules/toolchains/mingw64-x86_64.cmake
        - make
        - ../scripts/commit_result.sh i686-w64-mingw32 icu_cross
    stage: build
    only:
        - master

build:android-arm64-v8a:
    image: viaduck/ci:android
    script:
        - mkdir build-android-arm64-v8a
        - cd build-android-arm64-v8a
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=aarch64-linux-android -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
        - ../scripts/commit_result.sh arm64-v8a-android icu_cross
    stage: build
    only:
        - master
        
build:android-armeabi-v7a:
    image: viaduck/ci:android
    script:
        - mkdir build-android-armeabi-v7a
        - cd build-android-armeabi-v7a
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=arm-linux-androideabi -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=armeabi-v7a -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
        - ../scripts/commit_result.sh armeabi-v7a-android icu_cross
    stage: build
    only:
        - master
        
build:android-x86:
    image: viaduck/ci:android
    script:
        - mkdir build-android-x86
        - cd build-android-x86
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=i686-linux-android -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86 -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
        - ../scripts/commit_result.sh x86-android icu_cross
    stage: build
    only:
        - master
        
build:android-x86_64:
    image: viaduck/ci:android
    script:
        - mkdir build-android-x86_64
        - cd build-android-x86_64
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=x86_64-linux-android -DICU_BUILD_VERSION=$ICU_BUILD_VERSION -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_shared -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
        - ../scripts/commit_result.sh x86_64-android icu_cross
    stage: build
    only:
        - master
