image: viaduck/ci

stages:
    - build         # contains build and test and deploy

variables:
    ANDROID_PLATFORM: "android-26"
    ANDROID_NDK: "/android/ndk"
    
linux-x86_64:
    script:
        - mkdir build-linux-x86_64
        - cd build-linux-x86_64
        - cmake ../ -DBUILD_ICU=ON
        - make
    stage: build
    only:
        - master

windows-x86:
    image: viaduck/ci:mingw
    script:
        - mkdir build-windows-x86
        - cd build-windows-x86
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=i686-w64-mingw32
        - make
    stage: build
    only:
        - master

windows-x86_64:
    image: viaduck/ci:mingw
    script:
        - mkdir build-windows-x86_64
        - cd build-windows-x86_64
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=x86_64-w64-mingw32
        - make
    stage: build
    only:
        - master

android-arm64-v8a:
    image: viaduck/ci:android
    script:
        - mkdir build-android-arm64-v8a
        - cd build-android-arm64-v8a
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=aarch64-linux-android -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
    stage: build
    only:
        - master
        
android-armeabi-v7a:
    image: viaduck/ci:android
    script:
        - mkdir build-android-armeabi-v7a
        - cd build-android-armeabi-v7a
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=arm-linux-androideabi -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=armeabi-v7a -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
    stage: build
    only:
        - master
        
android-x86:
    image: viaduck/ci:android
    script:
        - mkdir build-android-x86
        - cd build-android-x86
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=i686-linux-android -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86 -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
    stage: build
    only:
        - master
        
android-x86_64:
    image: viaduck/ci:android
    script:
        - mkdir build-android-x86_64
        - cd build-android-x86_64
        - cmake ../ -DBUILD_ICU=ON -DICU_CROSS_ARCH=x86_64-linux-android -DANDROID_PLATFORM=$ANDROID_PLATFORM -DANDROID_ABI=x86_64 -DANDROID_TOOLCHAIN=clang -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake
        - make
    stage: build
    only:
        - master
